packages:
  - packages/*
  - sites/hypernova-site
  - sites/cilantro-site
  - sites/coglet-shuffle
  - sites/coglet-shuffle/astro-site
  - design-system-viewer

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - inotify
  - sharp
